version: "3.5"

services:
  postgres:
    image: postgres:13
    container_name: wallet_postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
    volumes:
      - /data/postgres/data:/var/lib/postgresql/data

    restart: always
    ports:
      - "5432:5432"

networks:
  default:
    external: true
    name: main

volumes:
  pgdata: {}
