# Generated by Django 3.2 on 2024-04-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('done', 'done')], max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw')], max_length=10),
        ),
    ]
