# Generated by Django 3.2 on 2024-04-10 19:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20240410_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='execute_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet'),
        ),
    ]
